Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EStore.Data;
using EStore.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using EStore.Services;

namespace EStore.Controllers
{
    [Authorize(Roles = "Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        public IConfiguration Configuration { get; }


        public CartController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            Configuration = configuration;

        }

        public async Task<IActionResult> Index()
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cart = await _context.Order.Where(o => o.UserId == user && o.status.Name == "InCart").Include(d => d.Details).ThenInclude(p => p.Product).FirstOrDefaultAsync();
            if (cart != null)
            {
                return View(cart);
            }
            else
            {
                return NoContent();
            }
        }


        public async Task<JsonResult> AddToCart(int id)
        {
            var user =  User.FindFirstValue(ClaimTypes.NameIdentifier);
            var Cart = await _context.Order.Where(e => e.User.Id == user && e.status.Name == "InCart").FirstOrDefaultAsync();
            var product = await _context.Product.Where(i => i.ProductId == id).FirstOrDefaultAsync();


            if (product == null)
            {
                return Json("Product Does not exist");
            }

            if(product.Stock == 0)
            {
                return Json("Product is out of stock");
            }

            if (Cart != null)
            {
                var item = await _context.OrderDetail.Where(i => i.OrderId == Cart.OrderId && i.ProductID == id).FirstOrDefaultAsync();
                if (item != null)
                {
                    item.Quantity++;
                    item.SubTotal = item.Quantity * product.Price;
                    _context.Update(item);
                }
                else
                {
                    var NewCartItem = new OrderDetail
                    {
                      Order = Cart,
                      ProductID = id,
                      Quantity = 1,
                      SubTotal = product.Price
                    };

                     await _context.AddAsync(NewCartItem);
                }

            }
            else
            {
                var order = new Order
                {
                    OrderStatusID = 1,
                    UserId = user
                };
                order.Details = new List<OrderDetail>
                {
                    new OrderDetail {ProductID = id, Quantity = 1, SubTotal = product.Price}
                };

                await _context.AddAsync(order);
            }
            product.Stock--;
            _context.Update(product);
            await _context.SaveChangesAsync();
            return Json(product.Name + " was added to cart");
        }

        public async Task<IActionResult> UpdateQuantity(int id, int quantity)
        {


            if (quantity == 0)
            {
                await DeleteFromCart(id);
            }
            else
            {
                var item = await _context.OrderDetail.Where(i => i.OrderDetailId == id).FirstOrDefaultAsync();
                var product = await _context.Product.Where(i => i.ProductId == item.ProductID).FirstOrDefaultAsync();

                if (item.Quantity < quantity && product.Stock > 0)
                {
                    product.Stock--;
                    item.Quantity = quantity;
                    item.SubTotal = product.Price * quantity;
                    _context.Update(item);
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                else if(item.Quantity > quantity)
                {
                    product.Stock++;
                    item.Quantity = quantity;
                    item.SubTotal = product.Price * quantity;
                    _context.Update(item);
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteFromCart(int id)
        {
            var item = await _context.OrderDetail.Where(i => i.OrderDetailId == id).FirstOrDefaultAsync();
            var product = await _context.Product.Where(i => i.ProductId == item.ProductID).FirstOrDefaultAsync();
            product.Stock += item.Quantity;
            _context.Remove(item);
            _context.Update(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Checkout(int id)
        {
            var order = await _context.Order.Where(i => i.OrderId == id).Include(d => d.Details).ThenInclude(p => p.Product).FirstOrDefaultAsync();
            if (order == null)
            {
                return NotFound();
            }
            order.Total = await _context.OrderDetail.Where(i => i.OrderId == id).SumAsync(t => t.SubTotal);
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(int id, [Bind("OrderId,BlockNo,RoadNo,BuildingNo,FlatNo")] Order orderChanges)
        {
            var order = await _context.Order.Where(i => i.OrderId == id).Include(u => u.User).FirstOrDefaultAsync();

            if (order.OrderId != orderChanges.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    order.BlockNo = orderChanges.BlockNo;
                    order.RoadNo = orderChanges.RoadNo;
                    order.BuildingNo = orderChanges.BuildingNo;
                    order.FlatNo = orderChanges.FlatNo;
                    order.Total = await _context.OrderDetail.Where(i => i.OrderId == id).SumAsync(t => t.SubTotal);
                    order.OrderStatusID++;
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                    string subject = "Order has been placed";
                    string body = "Your order #" + order.OrderId + " has been placed successfully";
                    var emailSender = new EmailsSender(Configuration);
                    emailSender.SendEmail(order.User.Email, subject, body);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (order == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("MyOrders", "Orders");
        }

    }
}

Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EStore.Data;
using EStore.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using EStore.Services;

namespace EStore.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnviornment;
        private FilesManager fileManager;

        public CategoriesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            
            _context = context;
            _webHostEnviornment = hostEnvironment;
            fileManager = new FilesManager(hostEnvironment);
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            // this will return the username
           //ViewData["UserName"] = HttpContext.User.Identity.Name;
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> CategoriesList()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Categories/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Name,Thumbnail")] Category category)
        {
            if (ModelState.IsValid)
            {
                if (category.Thumbnail != null)
                {
                    string path = "Images/Categories/" + category.Name + "/";
                    await fileManager.UploadFile(path, category.Thumbnail);
                    category.ThumbnailPath = fileManager.FilePath;
                }
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CategoriesList));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Name,Thumbnail")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (category.Thumbnail != null)
                    {
                        string path = "Images/Categories/" + category.Name + "/";
                        fileManager.DeleteFolder(path);
                        await fileManager.UploadFile(path, category.Thumbnail);
                        category.ThumbnailPath = fileManager.FilePath;
                    }
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(CategoriesList));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            _context.Category.Remove(category);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(CategoriesList));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/RolesController.cs
using EStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EStore.Controllers
{
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;

        public RolesController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Roles role)
        {
            var roleEXists = await roleManager.RoleExistsAsync(role.RoleName);
            if (!roleEXists)
            {
                var result = await roleManager.CreateAsync(new IdentityRole(role.RoleName));
            }
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Customer"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="MyOrders">My Orders</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Dashboard">Dashboard</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="CategoriesList">Manage Categories</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="ProductsList">Manage Products</a>
                            </li>
                            @*                            <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Roles" asp-action="Create">Add Roles</a>
                                </li>*@
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="ManageOrders">Manage Orders</a>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - EStore - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Pager.cshtml
@model EStore.Services.Pagination


<div class="container">
    @if (Model.TotalPages > 0)
    {
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-all-route-data="@Model.Parameters" asp-route-pg="1">First</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-all-route-data="@Model.Parameters" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>

            }


            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-all-route-data="@Model.Parameters" asp-route-pg="@pge"> @pge </a>
                </li>
            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-all-route-data="@Model.Parameters" asp-route-pg="@(Model.CurrentPage + 1)">Next</a>
                </li>

                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-all-route-data="@Model.Parameters" asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>

            }
        </ul>

    }
</div>