Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EStore.Data;
using EStore.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Configuration;
using EStore.Services;

namespace EStore.Controllers
{
    [Authorize(Roles = "Customer")]
    public class CartController : Controller
    {
        private readonly ApplicationDbContext _context;
        public IConfiguration Configuration { get; }


        public CartController(ApplicationDbContext context, IConfiguration configuration)
        {
            _context = context;
            Configuration = configuration;

        }

        public async Task<IActionResult> Index()
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var cart = await _context.Order.Where(o => o.UserId == user && o.status.Name == "InCart").Include(d => d.Details).ThenInclude(p => p.Product).FirstOrDefaultAsync();
            if (cart != null)
            {
                return View(cart);
            }
            else
            {
                return NoContent();
            }
        }


        public async Task<JsonResult> AddToCart(int id)
        {
            var user =  User.FindFirstValue(ClaimTypes.NameIdentifier);
            var Cart = await _context.Order.Where(e => e.User.Id == user && e.status.Name == "InCart").FirstOrDefaultAsync();
            var product = await _context.Product.Where(i => i.ProductId == id).FirstOrDefaultAsync();


            if (product == null)
            {
                return Json("Product Does not exist");
            }

            if(product.Stock == 0)
            {
                return Json("Product is out of stock");
            }

            if (Cart != null)
            {
                var item = await _context.OrderDetail.Where(i => i.OrderId == Cart.OrderId && i.ProductID == id).FirstOrDefaultAsync();
                if (item != null)
                {
                    item.Quantity++;
                    item.SubTotal = item.Quantity * product.Price;
                    _context.Update(item);
                }
                else
                {
                    var NewCartItem = new OrderDetail
                    {
                      Order = Cart,
                      ProductID = id,
                      Quantity = 1,
                      SubTotal = product.Price
                    };

                     await _context.AddAsync(NewCartItem);
                }

            }
            else
            {
                var order = new Order
                {
                    OrderStatusID = 1,
                    UserId = user
                };
                order.Details = new List<OrderDetail>
                {
                    new OrderDetail {ProductID = id, Quantity = 1, SubTotal = product.Price}
                };

                await _context.AddAsync(order);
            }
            product.Stock--;
            _context.Update(product);
            await _context.SaveChangesAsync();
            return Json(product.Name + " was added to cart");
        }

        public async Task<IActionResult> UpdateQuantity(int id, int quantity)
        {


            if (quantity == 0)
            {
                await DeleteFromCart(id);
            }
            else
            {
                var item = await _context.OrderDetail.Where(i => i.OrderDetailId == id).FirstOrDefaultAsync();
                var product = await _context.Product.Where(i => i.ProductId == item.ProductID).FirstOrDefaultAsync();

                if (item.Quantity < quantity && product.Stock > 0)
                {
                    product.Stock--;
                    item.Quantity = quantity;
                    item.SubTotal = product.Price * quantity;
                    _context.Update(item);
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                else if(item.Quantity > quantity)
                {
                    product.Stock++;
                    item.Quantity = quantity;
                    item.SubTotal = product.Price * quantity;
                    _context.Update(item);
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }

            }

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> DeleteFromCart(int id)
        {
            var item = await _context.OrderDetail.Where(i => i.OrderDetailId == id).FirstOrDefaultAsync();
            var product = await _context.Product.Where(i => i.ProductId == item.ProductID).FirstOrDefaultAsync();
            product.Stock += item.Quantity;
            _context.Remove(item);
            _context.Update(product);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Checkout(int id)
        {
            var order = await _context.Order.Where(i => i.OrderId == id).Include(d => d.Details).ThenInclude(p => p.Product).FirstOrDefaultAsync();
            if (order == null)
            {
                return NotFound();
            }
            order.Total = await _context.OrderDetail.Where(i => i.OrderId == id).SumAsync(t => t.SubTotal);
            return View(order);
        }

        [HttpPost]
        public async Task<IActionResult> Checkout(int id, [Bind("OrderId,BlockNo,RoadNo,BuildingNo,FlatNo")] Order orderChanges)
        {
            var order = await _context.Order.Where(i => i.OrderId == id).Include(u => u.User).FirstOrDefaultAsync();

            if (order.OrderId != orderChanges.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    order.BlockNo = orderChanges.BlockNo;
                    order.RoadNo = orderChanges.RoadNo;
                    order.BuildingNo = orderChanges.BuildingNo;
                    order.FlatNo = orderChanges.FlatNo;
                    order.Total = await _context.OrderDetail.Where(i => i.OrderId == id).SumAsync(t => t.SubTotal);
                    order.OrderStatusID++;
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                    string subject = "Order has been placed";
                    string body = "Your order #" + order.OrderId + " has been placed successfully";
                    var emailSender = new EmailsSender(Configuration);
                    emailSender.SendEmail(order.User.Email, subject, body);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (order == null)
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
            }
            return RedirectToAction("MyOrders", "Orders");
        }

    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EStore.Data;
using EStore.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using EStore.Services;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace EStore.Controllers
{
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnviornment;
        private readonly UserManager<ApplicationUser> _userManager;
        private FilesManager fileManager;
        public ProductsController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _webHostEnviornment = hostEnvironment;
            fileManager = new FilesManager(_webHostEnviornment);
            _userManager = userManager;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchString, string currentFilter, string sortOrder, int? CategoryId, int pg = 1)
        {

            if (searchString == null)
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["CategoryId"] = CategoryId;
            ViewData["sortOrder"] = sortOrder;


            var Parameters = new Dictionary<string, string>();
            Parameters.Add("CategoryId", CategoryId.ToString());
            Parameters.Add("sortOrder", sortOrder);
            Parameters.Add("CurrentFilter", searchString);


            this.ViewBag.ParametersDictionary = Parameters;

            var Products = from s in _context.Product
                        select s;
            Products = Products.Include(p => p.Category).Include(i => i.ImagesPaths.Take(1));

            if (CategoryId != null)
            {
                Products = Products.Where(d => d.CategoryId == CategoryId);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                Products = Products.Where(a => a.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "NameDecending":
                    Products = Products.OrderByDescending(s => s.Name);
                    ViewData["CurrSort"] = "Name: Z-A";
                    break;
                case "PriceAcending":
                    Products = Products.OrderBy(s => s.Price);
                    ViewData["CurrSort"] = "Price: Low-High";
                    break;
                case "PriceDecending":
                    Products = Products.OrderByDescending(s => s.Price);
                    ViewData["CurrSort"] = "Price: High-Low";
                    break;
                default:
                    Products = Products.OrderBy(s => s.Name);
                    ViewData["CurrSort"] = "Name: A-Z";
                    break;
            }

            const int pageSize = 9;
            if (pg < 1)
            {
                pg = 1;
            }

            int TotalRecords = Products.Count();
            var pager = new Pagination(TotalRecords, pg, pageSize);
            int SkippedRecords = (pg - 1) * pageSize;

            Products = Products.Skip(SkippedRecords).Take(pager.PageSize);

            pager.ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            pager.ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            this.ViewBag.Pager = pager;

            return View(await Products.ToListAsync());
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> ProductsList(string searchString, string currentFilter, string sortOrder, int? CategoryId, int pg = 1)
        {
            if (searchString == null)
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            ViewData["CategoryId"] = CategoryId;
            ViewData["sortOrder"] = sortOrder;


            var Parameters = new Dictionary<string, string>();
            Parameters.Add("CategoryId", CategoryId.ToString());
            Parameters.Add("sortOrder", sortOrder);
            Parameters.Add("CurrentFilter", searchString);


            this.ViewBag.ParametersDictionary = Parameters;

            var Products = from s in _context.Product
                           select s;
            Products = Products.Include(p => p.Category);

            if (CategoryId != null)
            {
                Products = Products.Where(d => d.CategoryId == CategoryId);
            }

            if (!String.IsNullOrEmpty(searchString))
            {
                Products = Products.Where(a => a.Name.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "NameDecending":
                    Products = Products.OrderByDescending(s => s.Name);
                    ViewData["CurrSort"] = "Name: Z-A";
                    break;
                case "PriceAcending":
                    Products = Products.OrderBy(s => s.Price);
                    ViewData["CurrSort"] = "Price: Low-High";
                    break;
                case "PriceDecending":
                    Products = Products.OrderByDescending(s => s.Price);
                    ViewData["CurrSort"] = "Price: High-Low";
                    break;
                default:
                    Products = Products.OrderBy(s => s.Name);
                    ViewData["CurrSort"] = "Name: A-Z";
                    break;
            }

            const int pageSize = 10;
            if (pg < 1)
            {
                pg = 10;
            }

            int TotalRecords = Products.Count();
            var pager = new Pagination(TotalRecords, pg, pageSize);
            int SkippedRecords = (pg - 1) * pageSize;

            Products = Products.Skip(SkippedRecords).Take(pager.PageSize);

            pager.ControllerName = this.ControllerContext.RouteData.Values["controller"].ToString();
            pager.ActionName = this.ControllerContext.RouteData.Values["action"].ToString();
            this.ViewBag.Pager = pager;

            return View(await Products.ToListAsync());
        }

        // GET: Products/Details/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.Category)
                .Include(i => i.ImagesPaths)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        public async Task<IActionResult> ProductPage(string name)
        {
            if (name == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .Include(p => p.Category)
                .Include(i => i.ImagesPaths)
                .FirstOrDefaultAsync(m => m.Name == name);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "Name");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create([Bind("ProductId,Name,Description,Cost,Price,Stock,CategoryId,Images")] Product product)
        {
            if (ModelState.IsValid)
            {
                if (product.Images != null)
                {
                    product.ImagesPaths = new List<ProductImage>();
                    string path = "Images/Products/" + product.Name + "/";

                    foreach (var file in product.Images)
                    {
                        await fileManager.UploadFile(path, file);
                        var ImagePath = new ProductImage()
                        {
                            Path = fileManager.FilePath
                        };
                        product.ImagesPaths.Add(ImagePath);
                    }
                }

                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ProductsList));
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "Name", product.CategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "Name", product.CategoryId);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.

Views/Cart/Checkout.cshtml
@model EStore.Models.Order

@{
    ViewData["Title"] = "Checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>Checkout</h4>
    <br />
    <a asp-controller="Cart" asp-action="Index" class="btn btn-primary float-left">Back to Cart</a>
    <br />

    <table class="table">
        <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Unit Price
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    SubTotal
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
            <tr>

                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTotal)
                </td>


            </tr>
            }
            <tr><td></td><td></td><td>Total:</td><td>@Model.Total BD</td></tr>
        </tbody>
    </table>
    <div class="row">
        <div class="col-md-12">
            <h4>Payment Details:</h4>
            <hr />
            <div class="col-4">
                <label class="control-label">Card Owner</label>
                <input type="text" class="form-control" required />
            </div>
            <div class="col-4">
                <label class="control-label">Card Number</label>
                <input type="number" class="form-control" required />
            </div>
            <div class="row">
                <div class="col-4">
                    <label class="control-label">Expiration Date</label>
                    <input type="month" class="form-control" required />
                </div>
                <div class="col-2">
                    <label class="control-label">CCV</label>
                    <input type="number" class="form-control" required />
                </div>
            </div>



        </div>
    </div>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <form asp-action="Checkout">
                <h4>Delivery Address:</h4>
                <hr />
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="OrderId" />
                <input type="hidden" asp-for="UserId" />
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="BlockNo" class="control-label"></label>
                            <input asp-for="BlockNo" class="form-control" required />
                            <span asp-validation-for="BlockNo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="RoadNo" class="control-label"></label>
                            <input asp-for="RoadNo" class="form-control" required />
                            <span asp-validation-for="RoadNo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="BuildingNo" class="control-label"></label>
                            <input asp-for="BuildingNo" class="form-control" required />
                            <span asp-validation-for="BuildingNo" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="form-group">
                            <label asp-for="FlatNo" class="control-label"></label>
                            <input asp-for="FlatNo" class="form-control" required />
                            <span asp-validation-for="FlatNo" class="text-danger"></span>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Place Order" class="btn btn-success btn-block" />
                </div>
            </form>
        </div>
    </div>


</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Cart/Index.cshtml
@model EStore.Models.Order

@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>Shopping Cart</h4>
    <br />
    <a asp-controller="Products" asp-action="Index" class="btn btn-primary float-left">Continue Shopping</a>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>
                    Product
                </th>
                <th>
                    Quantity
                </th>
                <th>
                    SubTotal
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Details)
            {
                <tr>

                    <td>
                        @Html.DisplayFor(modelItem => item.Product.Name)
                    </td>
                    <td>
                        <a asp-controller="Cart" asp-action="UpdateQuantity" asp-route-id="@item.OrderDetailId" asp-route-quantity="@(item.Quantity - 1)" class="btn btn-secondary">-</a>
                        @Html.DisplayFor(modelItem => item.Quantity)
                        <a asp-controller="Cart" asp-action="UpdateQuantity" asp-route-id="@item.OrderDetailId" asp-route-quantity="@(item.Quantity + 1)" class="btn btn-secondary">+</a>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubTotal)
                    </td>
                    <td>
                        <a asp-controller="Cart" asp-action="DeleteFromCart" asp-route-id="@item.OrderDetailId" class="btn btn-danger">Remove</a>
                    </td>

                </tr>
            }

        </tbody>
    </table>

</div>

<div>
    <a asp-controller="Cart" asp-action="Checkout" asp-route-id="@Model.OrderId" class="btn btn-success btn-block">Checkout</a>
</div>